#!/usr/bin/env bash

set -e

echo Adding repositories...
sudo add-apt-repository ppa:neovim-ppa/unstable -y
sudo add-apt-repository ppa:atareao/telegram -y

echo Updating repositories...
sudo apt-get update

echo Installing packages...

PACKAGES=(
    arandr
    autojump
    autotools-dev
    build-essential
    curl
    dkms
    direnv
    editorconfig
    exuberant-ctags
    git
    git-flow
    htop
    inotify-tools
    libevent-dev
    neovim
    nodejs
    npm 
    nfs-common
    redshift
    silversearcher-ag
    software-properties-common
    telegram
    tree
    wallch
    ubuntu-unity-desktop
    x11-xserver-utils
    xclip
    xsel
    zsh
    )

echo Installing ${PACKAGES[@]}
sudo apt-get install -y $(echo ${PACKAGES[@]})

echo Installing oh-my-zsh
if [[ ! -d ~/.oh-my-zsh ]]; then
	curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
fi

echo Remapping caps lock to control
sudo sed -i "s/XKBOPTIONS=\"\"/XKBOPTIONS=\"ctrl:nocaps\"/g" /etc/default/keyboard

echo Creating neovim symlinks
mkdir -p ~/.config
ln -sf ~/.nvim ~/.config/nvim

echo Installing blessed fonts
FONT_HOME=~/.local/share/fonts

test ~/.local/share/fonts/adobe-fonts/source-code-pro || {
	(git clone \
	   --branch release \
	   --depth 1 \
	   'https://github.com/adobe-fonts/source-code-pro.git' \
	   "$FONT_HOME/adobe-fonts/source-code-pro" && \
	fc-cache -f -v "$FONT_HOME/adobe-fonts/source-code-pro")
}

mkdir -p ~/Projects

test ~/Projects/rust || {
    git clone git@github.com:rust-lang/rust ~/Projects/rust
}
