#!/usr/bin/env bash

set -e

echo Adding repositories...
sudo add-apt-repository ppa:neovim-ppa/unstable -y

echo Updating repositories...
sudo apt-get update

echo Installing packages...
sudo apt-get install -y \
    autojump \
    curl \
    dkms \
    editorconfig \
    exuberant-ctags \
    git \
    git-flow \
    inotify-tools \
    neovim \
    nfs-common \
    python3-pip \
    python-dev \
    python-pip \
    python3-dev \
    redshift \
    silversearcher-ag \
    software-properties-common \
    wallch \
    xclip \
    xsel \
    zsh \
    htop

echo Installing oh-my-zsh
if [ ! -f ~/.oh-my-zsh ]; then
	curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
fi

echo Remapping caps lock to control
sudo sed -i "s/XKBOPTIONS=\"\"/XKBOPTIONS=\"ctrl:nocaps\"/g" /etc/default/keyboard

echo Installing stack
which stack
if [[ $? != 0 ]]; then
    curl -sSL https://get.haskellstack.org/ | sh -s - -f
    sudo mv /
fi

echo Installing Haskell tools
stack install hlint ghcid stylish-haskell

echo Installing rust
curl https://sh.rustup.rs -sSf >> rust-install.sh
bash rust-install.sh -y
rm rust-install.sh

mkdir -p ~/Projects

git clone git@github.com:rust-lang/rust ~/Projects/rust

echo Installing neovim python tools
pip3 install neovim
pip install neovim

echo Installing nix
curl https://nixos.org/nix/install | sh

echo Creating neovim symlinks
mkdir -p ~/.config
ln -sf ~/.nvim ~/.config/nvim

echo Installing PureScript
npm install -g purescript pulp bower
